cfile_gzip: fix type of gzopen return.
zlib 1.2.5 (on Fedora at least) typedefs gzFile to be a void *, so
this bug passed unnoticed.  1.2.7 (on Ubuntu at least) typedefs it to
struct gzFile_s *, so compile breaks:

cfile_gzip.c: In function ‘gzip_open’:
cfile_gzip.c:66:24: error: initialization from incompatible pointer type [-Werror]

Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>